### ISSUE TITLE
文档图片缺失

### ISSUE THREAD

**Issue by saxieyu** [alibaba/SREWorks#1]
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/71605/159408040-f3ca9c08-a918-4b64-b3df-ae790c7c453b.png">

**Comment by PengXingbo** [comment]
+1

**Comment by jacarrichan** [comment]
https://www.51cto.com/article/704515.html

**Comment by sreworks** [comment]
您好。源代码的部分的docs为生成gitbook的源文件，可能图片文件相对路径存在问题。
建议可以先看语雀版本的文档。https://www.yuque.com/sreworks-doc/docs

**Comment by Twwy** [comment]
gitbook生成文档的方式已经被移除，采用了docusaurus生成，没有summary.md能够在git上预览。点击 https://sreworks.opensource.alibaba.com/docs/ 直接浏览。
