### ISSUE TITLE
应用管理->应用开发->添加微服务组件失败

### ISSUE THREAD

**Issue by zhangleimxnavi** [alibaba/SREWorks#144]
应用管理->应用开发->添加微服务组件失败，如下图
![clipboard](https://user-images.githubusercontent.com/39846099/194691186-303641ef-735d-49d1-8dcd-dab8abf5d499.png)

后台报错如下：
![0CBB5FD1F819482397B3EBADC77A4EEA](https://user-images.githubusercontent.com/39846099/194691923-4cb5f372-a5bd-46b9-b9a8-a034075bcb9a.jpg)

团队管理中心已经配置了 gitlab 仓库地址
![012E306CD7214848B893BB7E6A8B05A1](https://user-images.githubusercontent.com/39846099/194691247-33c2b571-cf3c-4de2-abec-79e76a5141c2.jpg)

**Comment by zhangleimxnavi** [comment]
同样是创建组件，我在运维开发->后端开发->添加微服务组件就可以正常添加，如图：
![E09DF1EB0B5D495AAD729B742DC95D6C](https://user-images.githubusercontent.com/39846099/194691585-83062ddd-842b-4b93-a3ee-c6a1943d95cb.jpg)
发现该请求带了 gitlab的 user 和token
而之前 应用管理->应用开发->添加微服务组件，前端发送请求的时候 ，没有带gitlab的 user 和token
不知道是我部署的基础版的问题，还是其他问题

**Comment by Twwy** [comment]
感谢反馈，已经在测试环境复现该问题，预计本周修复，新版本应用会在运维市场中推送，可以点击升级修复。

**Comment by zhangleimxnavi** [comment]
感谢，so efficient~

**Comment by Twwy** [comment]
您好。在运维应用市场已经发布的了新的 应用管理 1.0.4，安装后即可解决问题。
另外团队管理也更新了版本 1.0.1，当保存源码库的时候会进行gitlab的读写校验，与运维应用中的保持一致。

**Comment by Twwy** [comment]
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/998191/195793646-e18f5c48-edd2-44cd-b7e9-f8e200173650.png">

**Comment by zhangleimxnavi** [comment]
> <img alt="image" width="1315" src="https://user-images.githubusercontent.com/998191/195793646-e18f5c48-edd2-44cd-b7e9-f8e200173650.png">

好嘞

**Comment by zhangleimxnavi** [comment]
> 您好。在运维应用市场已经发布的了新的 应用管理 1.0.4，安装后即可解决问题。 另外团队管理也更新了版本 1.0.1，当保存源码库的时候会进行gitlab的读写校验，与运维应用中的保持一致。

好嘞，收到
