### ISSUE TITLE
error: Dirty database version 88. Fix and force version.

### ISSUE THREAD

**Issue by kenchen1101** [alibaba/SREWorks#20]
部署：sreworks-appmanager-server时，初始化容器提示上面的错误，请问哪里可以跳过或者如何处理

**Comment by sreworks** [comment]
这是db-migration初始化的报错，如果数据可以丢弃的话，建议删除mysql对应pv/pvc，重新触发helm install或upgrade

**Comment by kenchen1101** [comment]
好的，我试试，谢谢
