### ISSUE TITLE
某些分辨率下右上角的菜单样式有问题

### ISSUE THREAD

**Issue by wangyumu** [alibaba/SREWorks#206]
当我缩放浏览器时，在80%的缩放比例下，右上角的菜单会隐藏起来，类似下拉的模式。这种模式下，弹出的菜单样式有问题，看不到文字。

![image](https://user-images.githubusercontent.com/11539396/223930243-0c8bef1a-04c0-429e-ac67-788901d1a94a.png)

**Comment by Antuw** [comment]
帮助发现问题，已处理
