### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by clcc2019** [alibaba/SREWorks#4]
![image](https://user-images.githubusercontent.com/46099295/159438296-06e49173-7ca0-4265-bbc2-feabbd6f222f.png)

**Comment by sreworks** [comment]
DOMAIN_BASE_INGRESS 变量依赖安装时候  `--set appmanager.home.url="https://your-website.***.com" ` 参数传入，如果您的k8s集群是不支持ingress的，NodePort方案还在优化适配，需要稍晚些提供出来。

**Comment by sreworks** [comment]
请注意 appmanager.home.url 参数上需要带 https:// 头
