### ISSUE TITLE
能否提供一套 docker-compose?  这样能快速预览项目功能

### ISSUE THREAD

**Issue by songangweb** [alibaba/SREWorks#7]
能否提供一套 docker-compose?  这样能快速预览项目功能

**Comment by yangpeng1994** [comment]
支持helm

**Comment by tianxiawuzhe** [comment]
同求docker-compose，helm不熟悉呀，本地也没有helm，也没有k8s，就只是纯的docker运行环境。我用【2.2 源码构建安装】未能编译成功，报了【Makefile:81: recipe for target 'controller-gen' failed
make: *** [controller-gen] Error 127】这种错误，也不知道该如何解决。。。

**Comment by sreworks** [comment]
1. 纯docker环境是无法运行的，SREWorks整体运行起来需要90+个Pod，docker-compose无法承载这些复杂调度，需要k8s集群才可以。
2. k8s环境在快速部署中推荐了kubesphere的all in one方案可以快速方便地搭建集群。

**Comment by sreworks** [comment]
> 同求docker-compose，helm不熟悉呀，本地也没有helm，也没有k8s，就只是纯的docker运行环境。我用【2.2 源码构建安装】未能编译成功，报了【Makefile:81: recipe for target 'controller-gen' failed make: *** [controller-gen] Error 127】这种错误，也不知道该如何解决。。。

controller-gen 的问题可能与您构建机器的os以及golang版本有关系，请提供一下对应的版本信息
